version: "3.5"
services:
  tabby:
    command: serve --model TabbyML/Codegen2-4B --device cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
